//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametri
    {
        public string Codice { get; set; }
        public string Valore { get; set; }
        public string Tipo { get; set; }
        public string Descrizione { get; set; }
        public string Gruppo { get; set; }
        public bool flgEditabile { get; set; }
    }
}
